name: Publish Caddy-On-Demand-TLS

on:
  push:
    branches: ['main']

jobs:
  publish:
    name: Build & Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22x'
      - uses: actions/checkout@v4
      - uses: ko-build/setup-ko@v0.7
      - run: ko build